### ISSUE TITLE
Feature Request/Fix

### ISSUE THREAD

**Issue by Brewcmas** [travisfoley/dfirtriage#6]
Ntuser.dat files not pulled, add option?

Deletes source event logs - option to keep?

**Comment by solomyr** [comment]
Hey Brewcmas, I added NTUSER.dat and $MFT collection. But I am having problems compiling the exe. 
Check this issue that I have. https://github.com/travisfoley/dfirtriage/issues/8

And here is my code if you are willing to try and compile it yourself: https://github.com/solomyr/DFIRTriageUpdate

**Comment by travisfoley** [comment]
solomyr... I really like your use of forecopy to grab the ntuser.dat and
$MFT.  I was originally going to be grabbing the $MFT, $USNJRNL:J, and
$LogFile but because of the size of the data decided to drop it.  Having it
available through an arg and not part of the default acquisition is a good
idea.  i'm going to take a closer look at your code and see if I can get it
to compile.

thanks!

**Comment by travisfoley** [comment]
Check out the new version (v5) just pushed today.
